name: Azure Static Web Apps CI/CD - Dev

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
      - '.github/workflows/**'
permissions:
  id-token: write
  contents: read
jobs:
  build_and_deploy_job:

    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true
          lfs: false
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: "Deploy Bicep File"
        uses: azure/arm-deploy@v1 
        with: 
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: dummy-1_group
          template: infrastructure/main.bicep
          parameters: 'infrastructure/parameters/dev.parameters.json repositoryToken=${{ secrets.REPO_TOKEN }}'
          failOnStdErr: false          
