name: Azure Static Web Apps CI/CD - Dev

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'infrastructure/parameters/dev.parameters.json' 
      - '.github\workflows'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Install Azure CLI
        run: |
          sudo apt-get update && sudo apt-get install -y azure-cli
    
      - name: Deploy with az bicep
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az bicep build --file 'infrastructure/main.bicep'
          az bicep deploy --resource-group dummy-1_group --template-file 'infrastructure/main.bicep' --parameters 'infrastructure/parameters/prod.parameters.json'


  close_pull_request_job:
    # if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_BEACH_0E770D610 }}
          action: "close"
