name: Azure Static Web Apps CI/CD - Prod

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
      - '.github/workflows'
    tags:
      - 'v*.*.*'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Azure Login
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Build Bicep
        run: az bicep build --file 'infrastructure/main.bicep'
  
      - name: Deploy with az bicep
        id: deploy
        run: |
          az deployment group create --resource-group dummy-1_group --template-file infrastructure/main.bicep --parameters 'infrastructure/parameters/prod.parameters.json' repositoryToken=${{ secrets.REPO_TOKEN }}
