name: Azure Static Web Apps CI/CD - Prod

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
      - '.github/workflows/**'
    tags:
      - 'v*.*.*'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false 
      - name: Azure Login
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: "Deploy Bicep File"
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: dummy-2_group
          template: infrastructure/main.bicep
          parameters: 'infrastructure/parameters/prod.parameters.json repositoryToken=${{ secrets.REPO_TOKEN }}'
          failOnStdErr: false 

      - name: Build App
        run: | 
          npm install
          npm run build
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_BUSH_0E6693D10 }}
          repo_token: ${{ secrets.REPO_TOKEN }}
          action: "upload"
          app_location: "./src"
          output_location: "build" 
          branch: "main"